---
new_page_extension: html
auto_deploy: false
admin_path: ''
webhook_url: https://api.stackbit.com/project/5f7304c18c45e90015c9c8b4/webhook/refresh-content
sections:
- type: heading
  label: header
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - STACKBIT_API_KEY=03589e2f546736dbf1231a77370e17d60af09e5805ad10c454afb93b2af71f39
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
